SotSF/conjurer

src/components/Canopy.tsx
src/patterns/shaders/black.frag

When there's no pattern being played, we can't see the canopy. This changes that to make the canopy render as black.
An alternate implementation would have a block and set the currentBlock to that.

render empty canopy as black

---

src/components/Timeline.tsx

(WARNING: includes commits from #12 and has that branch as merge base. Change merge base before merging!)
This lets your drag around the timeline cursor with the mouse, which is more satisfying to my brain than updating on click :P
I didn't do it in a very "react-y" way, but I wasn't exactly sure how best to do that while supporting drag events from outside the timeline ruler element.

Timeline ruler cursor drag

---

src/components/TimerControls.tsx
src/components/Waveform.tsx
src/types/Timer.ts

Before, clicking the Backward button while the song was playing would not actually make it restart the song.
Also, the progress display on the waveform wouldn't reset. I wasn't really sure why that was the case since it seems like lastCursorPosition should have been enough, but maybe globalTime might make more sense for calculating progress anyhow.
See in screenshot below that the progress got into a weird state (the blue part of the waveform is past the red arrow).

Fix Backward timer control button while song is playing 

---

src/components/TimerControls.tsx
src/components/Waveform.tsx
src/types/Timer.ts

Weird Mobx learning here: made lastCursor a reference such that it can cause reactions even when the underlying primitive isn't changed.

Make sure that changes to lastCursor are always observable

---

src/patterns/shaders/canopy.vert

Fixes the normal-to-intensity calculation in the canopy vertex shader

---

src/patterns/shaders/canopy.vert

With this change, the canopy vertex shader updates `gl_PointSize` based on the size of vector between gl point and camera.

points perspective

---

src/components/VariationControls.tsx
src/components/VariationGraph/ScalarVariationGraph.tsx
src/components/VariationGraph/VariationGraph.tsx
src/data/initialExperience.json
src/patterns/Disc.ts
src/patterns/Pulse.ts
src/patterns/shaders/pulse.frag
src/types/Variations/SineVariation.ts

it can do cool things
Also removed the recharts tooltip which was interfering with the normal chakra popover component behavior. Also implemented min/max for sine variations!

UI fixes / showing off the new pulse pattern

---

src/components/Canopy.tsx
src/components/DisplayCanvas.tsx
src/patterns/shaders/starfield.frag
src/shaders/conjurer_common.frag

This PR adds a ShaderChunk, which then becomes available for pattern artists to include common code with the `#include <conjurer_common>` directive.
Hopefully this way we can provide some useful stuff in there and reduce code duplication across patterns.

Conjurer common

---

.gitignore
package.json
src/components/CartesianView.tsx
src/components/Display.tsx
src/components/DisplayCanvas.tsx
src/components/MainControls.tsx
src/hooks/dataTransmission.ts
src/hooks/renderTarget.ts
src/scripts/websocketServer.ts
src/types/Store.ts
src/utils/websocket.ts
src/utils/websocketHost.ts
yarn.lock

Sends pixel data over a websocket connection! Enabled by clicking the "transmit"-looking button that is orange in this screenshot:
Sends data to `localhost:8080`.
Data is an `Uint8Array` with RGBA values. I've upped the pixels to 150x96, so each message would be 150x96x4 = 57.6 KB.
I think that they should be sending at a rate that is dependent on the refresh rate of your monitor. Currently no way to configure that.
For debugging purposes, you can run `yarn server` to run a server that will received data and once per second write an image `output.png` of what it sees.
Protip: toggling the conjurer transmit button off then on will reconnect to the websocket server which you need to do if you stop/start the server while the client is connected.

Data sending functionality

---

src/components/AddEffectButton.tsx
src/components/HeaderRepeat.tsx
src/components/ParameterView.tsx
src/components/PatternOrEffectBlock.tsx
src/components/TimelineBlockStack.tsx
src/components/TimelineLayerHeader.tsx
src/types/Block.ts

It is commonly the case that the block is so wide that you couldn't readily tell which pattern, effect, or parameter that you were editing because the header was centered and out of view. This change repeats headers every 1280px.

Header repeat for wide blocks

---

src/components/NewVariationButtons.tsx
src/components/PatternPlayground/PatternPlayground.tsx
src/components/VariationControls/AudioVariationControls.tsx
src/components/VariationControls/VariationControls.tsx
src/components/VariationGraph/ScalarVariationGraph.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
src/types/AudioStore.ts
src/types/Block.ts
src/types/Layer.ts
src/types/Store.ts
src/types/Variations/AudioVariation.ts
src/types/Variations/EasingVariation.ts
src/types/Variations/FlatVariation.ts
src/types/Variations/LinearVariation.ts
src/types/Variations/LinearVariation4.ts
src/types/Variations/PaletteVariation.ts
src/types/Variations/PeriodicVariation.ts
src/types/Variations/SplineVariation.ts
src/types/Variations/Variation.ts
src/types/Variations/variations.ts
src/types/audioPeaks.ts

Audio data is now available to variations! We can do some more sophisticated things with it, but with this change we create a simple audio variation which can be used to map a parameter to that audio data. You can apply a factor and an offset to the audio "peak".

Audio reactive variations

---

src/effects/shaders/shaper.frag
src/effects/shaders/tiler.frag
src/patterns/shaders/convergence.frag
src/shaders/conjurer_common.frag

A follow up improvement to https://github.com/SotSF/conjurer/pull/175. What I historically referred to as cartesian is a little atypical since it goes from -0.5 to 0.5, when most of the time with shader programming it goes from -1 to 1. We'll call the first case "half cartesian" and the second one "cartesian" from now on.

Improve conjurer common coordinate systems

---

src/components/AudioControls.tsx
src/components/BeatGrid.tsx
src/components/BeatGridOverlay.tsx
src/components/BeatMapperPage.tsx
src/components/Menu/MenuBar.tsx
src/components/Timeline.tsx
src/components/TimelineBlockBound.tsx
src/components/TimelineBlockStack.tsx
src/components/VariationBound.tsx
src/types/AudioStore.ts
src/types/Block.ts
src/types/SongMetadata.ts
src/types/UIStore.ts

Now blocks and variations can be snapped to a beat grid!

Arrangement view beat grid with snapping

---

src/components/PatternOrEffectBlock.tsx
src/components/PatternTimingModal.tsx
src/components/VariationControls/VariationControls.tsx
src/patterns/SpaceOdyssey.ts
src/patterns/patterns.ts
src/patterns/shaders/spaceOdyssey.frag
src/shaders/conjurer_common.frag
src/types/Variations/PeriodicVariation.ts

- Introduced a new `SpaceOdyssey` pattern which I ripped off from a YouTube video lulz
- Added the `PatternTimingModal` to make it simpler to specify exactly where in the song a pattern should start/stop. Accessible via a new clock icon in the pattern header
- Made the pattern name always visible (was previously grayed out if the pattern wasn't selected in the UI)
- Fixed an issue with the `PeriodicVariationControls` which could break the component if the user enters a non-numeric string (the component was setting the parameter value to `NaN` when I entered a minus sign, and could not easily recover from it)

`SpaceOdyssey` pattern, support manual timing configuration

---

README.md
src/components/Canvas/CanopyView.tsx
src/components/Canvas/DisplayCanvas.tsx
src/components/RenderPipeline/BlockStackNode.tsx
src/components/RenderPipeline/RenderPipeline.tsx

This has been bothering me forever. At certain moments in experiences under certain conditions, there would be this telltale lurch/jarring "off" frame. Finally founds the fix. Now we will always render to the same final render target ("renderTargetZ"). Before, when you would go between one and two active layers, the final output render target would need to be switched, which we were doing with an useEffect. Because the effect runs afterwards, it was in practice _sometimes_ too low and resulted in the "off" frame. Phewww

Rendering pipeline bug fix 

---

package.json
src/scripts/try-start-unity-bridge.sh

This changes `yarn dev` to search for a built ConjurerBridge application in `/Applications`, then launches the latest version if it finds one. This should make the startup process for the MC persona simpler.
Built ConjurerBridge binaries can be [found eg here](https://github.com/SotSF/canopy-unity/releases/tag/conjurer_bridge_osx_v0.0.4)

Try to find and launch the built ConjurerBridge application

---

README.md
src/db/local.ts
src/db/prod.ts

This avoids an error when trying to connect to a local database in production.

Only connect databases when used

---

migrations/0003_empty_valeria_richards.sql
migrations/meta/0003_snapshot.json
migrations/meta/_journal.json
package.json
src/components/ExperiencesTable/ExperiencesTable.tsx
src/components/Menu/OpenExperienceModal.tsx
src/components/PlaylistEditor/AddExperienceModal.tsx
src/components/PlaylistEditor/PlaylistEditor.tsx
src/db/schema.ts
src/hooks/experience.ts
src/hooks/experiencesAndUsers.ts
src/scripts/tursoMigration.ts
src/server/routers/experienceRouter.ts
src/server/routers/playlistRouter.ts
src/types/Experience.ts
src/types/ExperienceStore.ts
src/types/Store.ts
yarn.lock

This is a noop refactor purely for styling and DRYing it up:
```
$ yarn db:generate
yarn run v1.22.19
$ drizzle-kit generate --config=drizzle-local.config.ts
Reading config file '/Users/jeff/code/sotsf/conjurer/drizzle-local.config.ts'
5 tables
experiences 8 columns 2 indexes 0 fks
playlists 8 columns 1 indexes 1 fks
songs 6 columns 1 indexes 0 fks
users 5 columns 1 indexes 0 fks
users_to_experiences 5 columns 1 indexes 2 fks
No schema changes, nothing to migrate 😴
✨  Done in 0.43s.
```

refactor: put createdAt and updatedAt into a reusable block

---

src/server/routers/playlistRouter.ts
src/types/Playlist.ts

Now the MC page will have a slightly better experience for new users to conjurer: the first playlist that gets selected is an auto generated playlist that includes all finished experiences, called "Welcome to Conjurer". The playlist order is shuffled on every load.
Closes https://github.com/SotSF/conjurer/issues/329

Introduce "welcome to conjurer" smart playlist that includes all finished experiences 

---

migrations/0005_outgoing_hedge_knight.sql
migrations/meta/0005_snapshot.json
migrations/meta/_journal.json
src/components/Canvas/CartesianSpaceView.tsx
src/components/Canvas/DisplayCanvas.tsx
src/components/ExperienceEditor/ExperienceEditorControls.tsx
src/components/ExperienceThumbnail.tsx
src/components/Menu/MenuBar.tsx
src/components/Menu/OpenExperienceModal.tsx
src/components/PlaylistEditor/PlaylistEditor.tsx
src/components/PlaylistEditor/PlaylistItem.tsx
src/db/schema.ts
src/hooks/captureThumbnail.ts
src/hooks/experience.ts
src/server/routers/experienceRouter.ts
src/server/routers/playlistRouter.ts
src/types/Experience.ts
src/types/ExperienceStore.ts
src/types/Store.ts
src/types/UIStore.ts

Closes #328 
Introduces experience thumbnails! Such a great idea by @jeffawang.
From the experience editor page, you simply click the camera icon next to the experience name to save the thumbnail.
They are being saved as data URLs for now, but we can store them in s3 in the future.

Experience thumbnails

---

src/components/ExperienceEditor/ExperienceEditorPage.tsx
src/components/ExperienceThumbnail.tsx
src/components/KeyboardControls.tsx
src/components/LoadingOverlay.tsx
src/components/LoginButton.tsx
src/components/Menu/MenuBar.tsx
src/components/Menu/OpenExperienceModal.tsx
src/components/PlaygroundPage.tsx
src/components/PlaylistEditor/PlaylistEditor.tsx
src/components/PlaylistEditor/PlaylistEditorPage.tsx
src/components/PlaylistEditor/PlaylistItem.tsx
src/components/RoleSelector.tsx
src/types/ExperienceStore.ts
src/types/Store.ts

Closes #334, #335, #343
Improves the navigation UX, including showing the loading overlay while initializing the app and loading an experience. Should also fix all of the browser back/forward navigation issues.

Initial loading state / better navigation
