modules/common/types/Block.ts
modules/common/types/Pattern.ts
modules/common/types/PatternParams.ts
modules/components/BlockView.tsx
modules/components/Editor.tsx
modules/patterns/GradientPattern.ts
modules/patterns/Patterns.ts

Playing with types and trying out some new ways to update the parameters.

add proxy thing and update generics implementation

---

modules/common/types/Block.ts
modules/common/types/Store.ts
modules/common/types/Timer.ts
modules/common/utils/size.ts
modules/components/BlockView.tsx
modules/components/Display.tsx
modules/components/Editor.tsx
modules/components/Layer.tsx
modules/components/PatternList.tsx
modules/components/SelectablePattern.tsx
modules/components/Timeline.tsx
modules/components/TimelineBlock.tsx
modules/patterns/Patterns.ts
modules/patterns/Rainbow.ts
modules/patterns/shaders/gradient.frag
modules/patterns/shaders/rainbow.frag
modules/patterns/shaders/sunCycle.frag

Another PR where going commit by commit could be helpful.

Pattern list, global timer

---

README.md
modules/common/types/Block.ts
modules/common/types/Store.ts
modules/common/types/Timer.ts
modules/components/BlockView.tsx
modules/components/Editor.tsx
modules/components/KeyboardListener.tsx
modules/components/Layer.tsx
modules/components/LayerBlocks.tsx
modules/components/PatternList.tsx
modules/components/SelectablePattern.tsx
modules/components/TimeMarker.tsx
modules/components/Timeline.tsx
modules/components/TimelineBlock.tsx
modules/components/TimelineBlockBound.tsx
modules/components/TimerReadout.tsx
package.json
styles/TimeMarker.module.css
yarn.lock

Blocks can be added from the pattern list now, as well as resized!
Noticing some performance problems, which I will work on in this branch.

Timeline block features

---

modules/common/types/Block.ts
modules/common/types/Pattern.ts
modules/common/types/Store.ts
modules/common/types/Timer.ts
modules/common/utils/object.ts
modules/common/utils/time.ts
modules/components/BlockView.tsx
modules/components/Controls.tsx
modules/components/Editor.tsx
modules/components/Keyboard.tsx
modules/components/KeyboardListener.tsx
modules/components/PatternList.tsx
modules/components/Ruler.tsx
modules/components/SelectablePattern.tsx
modules/components/TimeMarker.tsx
modules/components/Timeline.tsx
modules/components/TimelineBlock.tsx
modules/patterns/GradientPattern.ts
modules/patterns/Rainbow.ts
modules/patterns/SunCycle.ts

Lots of small tweaks in this one, but mainly worked on copying/pasting/duplicating/moving blocks around. Also added some instructions!

Miscellaneous optimizations

---

modules/common/types/Store.ts
modules/common/utils/algorithm.ts
modules/components/BlockView.tsx
modules/components/CanopyView.tsx
modules/components/Display.tsx
modules/components/Editor.tsx
modules/components/Keyboard.tsx
modules/components/Timeline.tsx
modules/components/TimelineBlock.tsx
modules/patterns/shaders/canopy.vert
modules/patterns/shaders/default.vert
modules/patterns/shaders/gradient.frag
modules/patterns/shaders/rainbow.frag
modules/patterns/shaders/sunCycle.frag

More stuff

---

package.json
src/components/Controls.tsx
src/components/ShaderWaveform.tsx
src/components/Timeline.tsx
src/components/Waveform.tsx
src/components/WavesurferWaveform.tsx
src/patterns/shaders/black.frag
src/patterns/shaders/waveform.frag
src/types/UIStore.ts
yarn.lock

this does render a waveform with a shader tho
unfortunately i am not smart enough to Do A React Fiber MobX UiState so it doesn't respond to scroll events or nothin'

lmao glsl is hot garbage

---

package.json
src/components/Arrangement.tsx
src/components/Editor.tsx
src/components/Layer.tsx
src/components/PlayHead.tsx
src/components/Ruler.tsx
src/components/Timeline.tsx
src/components/WavesurferWaveform.tsx
src/hooks/wheelZooming.ts
src/types/UIStore.ts
src/utils/time.ts
styles/globals.css
yarn.lock

Definitely still more work to do, but horizontally scrolling is possible now! (note that the time does not start at 0)

Scrollable timeline

---

package.json
src/components/ParametersList.tsx
src/components/TimelineBlock.tsx
src/types/Store.ts
yarn.lock

Partially implemented "pattern variations" - our way of modifying uniforms overtime. I'm using a charting library called `recharts`. https://recharts.org/en-US
It seemed like a good balance of things: lightweight, react-centric, easily configured for our use case.
The plots you see above are just mock plots for now. Next up: be able to select from a set of easing functions the parameter variation that you desire.

Pattern variations!

---

README.md
package.json
pages/_app.tsx
src/components/NewVariationButtons.tsx
src/components/Parameter.tsx
src/components/ParametersList.tsx
src/components/Ruler.tsx
src/components/VariationControls.tsx
src/components/VariationGraph.tsx
src/patterns/Disc.ts
src/patterns/shaders/disc.frag
src/types/PatternParams.ts
src/types/Store.ts
src/types/Variations/LinearVariation4.ts
src/types/Variations/Variation.ts
src/utils/color.ts
src/utils/time.ts
styles/variationControls.css
yarn.lock

Now you can vary color over time 🌈

More patterns and variations

---

package.json
src/components/CanopyCanvas.tsx
src/components/Controls.tsx
src/components/Parameter.tsx
src/components/ParametersList.tsx
src/components/TimelineBlock.tsx
src/components/TimelineBlockBound.tsx
src/components/VariationBound.tsx
src/components/VariationControls.tsx
src/components/VariationGraph.tsx
src/components/WavesurferWaveform.tsx
src/types/UIStore.ts
src/utils/color.ts
yarn.lock

Just a number of small improvements. The most interesting is bringing in the react three fiber performance overlay:

Small fixes, performance overlay

---

package.json
src/components/Controls.tsx
src/components/WavesurferWaveform.tsx
src/types/Store.ts
src/utils/audio.ts
yarn.lock

Exposing mp3s publicly in an S3 bucket. Happy to include any audio that people are interested in!

Selectable music

---

src/components/ParameterVariations.tsx
src/components/ParameterView.tsx
src/components/ParametersList.tsx
src/components/PlayHead.tsx
src/components/VariationBound.tsx
src/components/VariationControls.tsx
src/components/VariationGraph/LinearVariationGraph4.tsx
src/components/VariationGraph/ScalarVariationGraph.tsx
src/components/VariationGraph/VariationGraph.tsx
src/patterns/shaders/clouds.frag
src/utils/layout.ts

Cleaned up the variations controls a bit more - now you can drag the border of the variation graph to change its duration.

More timeline features

---

src/patterns/LogSpirals.ts
src/patterns/patterns.ts
src/patterns/shaders/logSpirals.frag

Here's a shader I wrote that does some fun log-spiral-y stuff. Noticed a couple things:
- the UX for a shader with many parameters gets pretty whack (runs off the bottom of the page, scrolling competes with moving the timeline area)
- Getting a bunch of localStorage related errors:
```
367 |
368 |   saveToLocalStorage = (key: string) => {
> 369 |     localStorage.setItem(key, JSON.stringify(this.serialize()));
|    ^
370 |   };
371 |
372 |   serialize = () => ({
error - src/types/Store.ts (369:4) @ localStorage
error - uncaughtException: Error [ReferenceError]: localStorage is not defined
at Store.saveToLocalStorage (webpack-internal:///./src/types/Store.ts:297:13)
at executeAction (/home/kevin/code/conjurer/node_modules/mobx/dist/mobx.cjs.development.js:1080:15)
at …
```

Pls enjoy these spirals

---

src/components/PatternList.tsx
src/components/SelectablePattern.tsx
src/components/TimelineBlock.tsx
src/components/TimelineBlockBound.tsx
src/components/TimelineBlockEffects.tsx
src/effects/effects.ts
src/types/Block.ts
src/types/Store.ts

Allow adding, removing, and reordering effects. Except the only available effect is color tint, which is a travesty. We need more effects!

Becoming more effectual

---

src/components/Controls.tsx
src/components/ParameterView.tsx
src/components/PlayHead.tsx
src/components/RenderPipeline.tsx
src/components/SelectablePattern.tsx
src/components/Timeline.tsx
src/components/TimerReadout.tsx
src/data/initialExperience.json
src/effects/CartesianProjection.ts
src/effects/effects.ts
src/effects/shaders/cartesianProjection.frag
src/patterns/LogSpirals.ts
src/types/Block.ts
src/types/Store.ts
src/types/Timer.ts
src/types/UIStore.ts

Now the log spiral is fully glorious.

Cartesian effect!

---

README.md
package.json
pages/index.tsx
src/components/App.tsx
src/components/Canopy.tsx
src/components/Keyboard.tsx
src/components/NewVariationButtons.tsx
src/components/ParameterVariations.tsx
src/components/ParameterView.tsx
src/components/TimelineBlock.tsx
src/components/VariationControls.tsx
src/components/VariationGraph/ScalarVariationGraph.tsx
src/components/VariationGraph/SplineVariationGraph.tsx
src/components/VariationGraph/VariationGraph.tsx
src/components/VariationHandle.tsx
src/components/WavesurferWaveform.tsx
src/data/initialExperience.json
src/patterns/shaders/canopy.vert
src/types/CanvasSpliner.d.ts
src/types/Store.ts
src/types/Variations/SplineVariation.ts
src/types/Variations/Variation.ts
src/types/Variations/variations.ts
src/utils/object.ts
src/utils/size.ts
styles/variationGraph.css
yarn.lock

Editable spline variation

---

src/effects/Rotate.ts
src/effects/effects.ts
src/effects/shaders/rotate.frag

Add rotate effect

---

src/patterns/Pulse.ts
src/patterns/patterns.ts
src/patterns/shaders/pulse.frag

Needs parameters, but I am le tired

Pulse pattern

---

src/components/NewVariationButtons.tsx
src/types/Block.ts
src/types/Pattern.ts
src/types/PatternParams.ts

the proxy thing was fun, but it's time to move on

remove paramvalues abstraction, it was too complicated

---

package.json
src/components/Timeline.tsx
src/components/WavesurferWaveform.tsx
yarn.lock

Finish implementing audio looping

---

src/components/ParameterVariations.tsx
src/components/VariationControls.tsx
src/components/VariationGraph/SplineVariationGraph.tsx
src/components/VariationHandle.tsx
src/types/Variations/SplineVariation.ts

Same popover menu, which needs improvement, now accessible from a gear. Couldn't get the popover to open when clicking the spline canvas, hence this approach.

Spline domains

---

src/data/initialExperience.json
src/patterns/Fire.ts
src/patterns/Melt.ts
src/patterns/patterns.ts
src/patterns/shaders/fire.frag
src/patterns/shaders/melt.frag

Both could use some more work. Ported them from shader toy.

Fire and melt patterns

---

src/effects/ColorTint.ts
src/effects/Leaf.ts
src/effects/Rotate.ts
src/effects/Shaper.ts
src/effects/shaders/leaf.frag
src/patterns/Barcode.ts
src/patterns/Clouds.ts
src/patterns/Disc.ts
src/patterns/Fire.ts
src/patterns/LogSpirals.ts
src/patterns/Melt.ts
src/patterns/Pulse.ts
src/patterns/SunCycle.ts
src/patterns/Tunnel.ts
src/patterns/patterns.ts
src/patterns/shaders/melt.frag
src/patterns/shaders/tunnel.frag
src/types/Store.ts

We're now using two patterns derived from Dag Agren ([shadertoy](https://www.shadertoy.com/user/WAHa_06x36)). This one is called tunnel, and I think it needs a little more tuning to look its best on the canopy, but it already looks pretty cool.
I reached out to him on Mastodon and he gave use express permission to use his stuff! He just asked that we give credit.

New tunnel pattern

---

README.md
pages/_app.tsx
src/components/AddEffectButton.tsx
src/components/LayerOpacityVariations.tsx
src/components/NewVariationButtons.tsx
src/components/ParameterView.tsx
src/components/ParametersList.tsx
src/components/PatternPlayground/ParameterControls.tsx
src/components/PatternPlayground/PatternList.tsx
src/components/PatternPlayground/PatternPlayground.tsx
src/components/PatternPlayground/SelectablePattern.tsx
src/components/RenderPipeline/BlockStackNode.tsx
src/components/RenderPipeline/RenderPipeline.tsx
src/components/TimelineBlockStack.tsx
src/components/TimelineLayer.tsx
src/components/VariationGraph/VariationGraph.tsx
src/components/WavesurferWaveform.tsx
src/data/initialExperience.json
src/patterns/Pulse.ts
src/patterns/shaders/pulse.frag
src/types/AudioStore.ts
src/types/Block.ts
src/types/ExperienceStore.ts
src/types/Layer.ts
src/types/Pattern.ts
src/types/PatternParams.ts
src/types/Store.ts
src/types/Timer.ts
styles/WavesurferWaveform.module.css
styles/waveform.css

Did lots of playing around and while attempting to make a cool thing tried to fix the bugs/UX issues that I encountered. Still [a ways to go](https://github.com/SotSF/conjurer/wiki).

Dog fooding / so many bugfixes

---

src/components/NewVariationButtons.tsx
src/components/ParameterVariations.tsx
src/components/PlayHead.tsx
src/components/ScalarInput.tsx
src/components/TimelineLayerHeader.tsx
src/components/VariationControls.tsx
src/components/VariationGraph/LinearVariationGraph4.tsx
src/components/VariationGraph/ScalarVariationGraph.tsx
src/components/VariationGraph/SplineVariationGraph.tsx
src/components/VariationGraph/VariationGraph.tsx
src/components/VariationHandle.tsx
src/data/initialExperience.json
src/effects/Rotate.ts
src/effects/shaders/rotate.frag
src/patterns/Pulse.ts
src/patterns/shaders/pulse.frag
src/types/Block.ts
src/types/Layer.ts
src/types/Store.ts
src/types/Variations/FlatVariation.ts
src/types/Variations/LinearVariation.ts
src/types/Variations/LinearVariation4.ts
src/types/Variations/PeriodicVariation.ts
src/types/Variations/SplineVariation.ts
src/types/Variations/Variation.ts
styles/variationControls.css

Replace popover with sidebar controls

---

src/components/DisplayCanvas.tsx
src/components/RenderOnTimeChange.tsx
src/components/RenderPipeline/BlockStackNode.tsx
src/components/RenderPipeline/RenderPipeline.tsx

Phew, had to dive deep to fix this one. I've learned that reusing render target textures excessively can make for difficult debugging! Left some on demand frame rendering stuff around in case we need to debug in the future.

Fix layer effect bug

---

src/types/Store.ts
src/types/UIStore.ts

Longtime bug that I finally figured out how to fix

Play head zoom bug

---

src/components/AudioControls.tsx
src/components/Menu/SaveExperienceModal.tsx
src/components/UploadAudioModal.tsx
src/types/AudioStore.ts
src/types/UIStore.ts

Upload audio functionality

---

src/components/KeyboardControls.tsx
src/effects/Tiler.ts
src/effects/effects.ts
src/effects/shaders/shaper.frag
src/effects/shaders/tiler.frag
src/patterns/Pulse.ts
src/patterns/shaders/globules.frag
src/patterns/shaders/pulse.frag
src/patterns/shaders/starfield.frag
src/shaders/conjurer_common.frag

Tiling effect work in progress

Pattern and effects touchups

---

src/effects/CloudsMask.ts
src/effects/Tiler.ts
src/effects/effects.ts
src/effects/shaders/cloudsMask.frag
src/effects/shaders/tiler.frag
src/patterns/Clouds.ts
src/patterns/shaders/clouds.frag
src/patterns/shaders/pulse.frag
src/shaders/conjurer_common.frag

Improved Clouds pattern:
Added CloudsMask effect:
Improved Tiler effect:

More pattern and effect improvements

---

src/components/DisplayCanvas.tsx
src/components/PatternPlayground/PatternPlayground.tsx
src/components/PatternPlayground/PreviewCanvas.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
yarn.lock

Also pulling in the change to fix wavesurfer dragging.

Cartesian view in playground

---

src/effects/ConstructMask.ts
src/effects/effects.ts
src/effects/shaders/constructMask.frag
src/patterns/Construct.ts
src/patterns/patterns.ts
src/patterns/shaders/construct.frag
src/shaders/conjurer_common.frag

New construct pattern/effect

---

.gitignore
README.md
package.json
pages/api/audio.ts
pages/api/experiences.ts
pages/api/experiences/[experienceFilename].ts
src/components/AudioControls.tsx
src/components/MainControls.tsx
src/components/Menu/OpenExperienceModal.tsx
src/components/RenderPipeline/RenderPipeline.tsx
src/components/UserPicker.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
src/hooks/experiences.ts
src/scripts/downloadCloudAssets.ts
src/types/AudioStore.ts
src/types/ExperienceStore.ts
src/types/Store.ts
src/utils/assets.ts

Partially addresses #109, next up is saving experiences locally.

Local asset functionality: loading experiences and audio

---

pages/api/experiences/[experienceFilename].ts
src/components/KeyboardControls.tsx
src/components/Menu/MenuBar.tsx
src/components/Menu/SaveExperienceModal.tsx
src/types/ExperienceStore.ts

Resolves #109! Now you can save your experiences locally.

Implement saving files locally

---

src/components/LayerOpacityVariations.tsx
src/components/NewVariationButtons.tsx
src/components/ParameterView.tsx
src/components/PatternPlayground/ParameterControls.tsx
src/components/PatternPlayground/PatternPlayground.tsx
src/components/VariationControls.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
src/effects/CartesianProjection.ts
src/effects/shaders/cartesianProjection.frag
src/types/AudioStore.ts
src/types/Block.ts
src/types/Variations/EasingVariation.ts
src/types/Variations/Variation.ts
src/utils/easings.ts

Some fun stuff:
* animation to show that audio is loading
* playground now shows controls for effects
* you can smoothly project from canopy space to cartesian space with cartesian projection `cartesianness` uniform
* added easing variations! all of the ones on this page: https://easings.net/

Various UI updates

---

src/components/PatternPlayground/ColorParameterControl.tsx
src/components/PatternPlayground/ParameterControls.tsx
src/components/PatternPlayground/ScalarParameterControl.tsx

cc @justynaipham editable colors! 🌈

Playground color parameter control

---

src/components/Arrangement.tsx
src/components/PalletteEditor/PaletteEditor.tsx
src/components/PalletteEditor/PaletteEditorModal.tsx
src/components/ParameterValue.tsx
src/components/ParameterView.tsx
src/components/PatternPlayground/ColorParameterControl.tsx
src/components/PatternPlayground/PaletteParameterControl.tsx
src/components/PatternPlayground/ParameterControls.tsx
src/components/PatternPlayground/PatternPlayground.tsx
src/components/PatternPlayground/ScalarParameterControl.tsx
src/components/TimelineLayerHeader.tsx
src/components/VariationControls/PaletteVariationControls.tsx
src/components/VariationControls/VariationControls.tsx
src/components/VariationGraph/LinearVariationGraph4.tsx
src/components/VariationGraph/PaletteVariationGraph.tsx
src/components/VariationGraph/ScalarVariationGraph.tsx
src/components/VariationGraph/VariationGraph.tsx
src/types/Palette.ts
src/types/UIStore.ts

Now you can edit the palette in the playground, but there is only a "randomize" button for now. Basically just copying this: http://dev.thi.ng/gradients/
You can also edited from the arrangement view:

Pallette editor

---

src/components/PalletteEditor/PaletteEditor.tsx
src/utils/color.ts

Pretty ugly UI at the moment. We can touch it up as we add more palette controls.

Palette: randomize with seed color

---

.prettierrc
pages/playground.tsx
src/components/NewVariationButtons.tsx
src/components/ParameterValue.tsx
src/components/PatternPlayground/ColorParameterControl.tsx
src/components/PatternPlayground/PaletteParameterControl.tsx
src/components/PatternPlayground/ParameterControl.tsx
src/components/PatternPlayground/ParameterControlName.tsx
src/components/PatternPlayground/ParameterControls.tsx
src/components/PatternPlayground/PatternList.tsx
src/components/PatternPlayground/PatternPlayground.tsx
src/components/PatternPlayground/ScalarParameterControl.tsx
src/components/PatternPlayground/SelectablePatternEffect.tsx
src/types/PatternParams.ts

Redesigned this page a bit in order to fit more parameters on the left. Color and palette parameters still need some work. Open to further changing this if you don't like anything @justynaipham !

Playground page redesign

---

src/components/KeyboardControls.tsx
src/components/Menu/MenuBar.tsx
src/data/emptyExperience.json
src/types/ExperienceStore.ts
src/types/Store.ts

New experience menu item

---

src/components/PatternOrEffectBlock.tsx
src/components/PatternPlayground/ScalarParameterControl.tsx
src/effects/Tiler.ts
src/patterns/Convergence.ts
src/patterns/PulsePalette.ts
src/patterns/patterns.ts
src/patterns/shaders/convergence.frag
src/patterns/shaders/pulsePalette.frag
src/types/AudioStore.ts

PulsePalette pattern, playground improvements

---

src/components/AudioControls.tsx
src/components/MarkerEditorModal.tsx
src/components/Timeline.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
src/types/AudioStore.ts
src/types/UIStore.ts
src/utils/color.ts

Doesn't persist yet, and the way of creating them (pencil button, click on timeline) and editing them (double clicking marker when pencil is NOT active) needs a lot of improvement, but at least functional.

Marker functionality

---

src/components/KeyboardControls.tsx
src/components/ParameterVariations.tsx
src/components/Timeline.tsx
src/components/TimelineBlockStack.tsx
src/components/TimelineLayer.tsx
src/components/TimelineLayerHeader.tsx
src/components/VariationGraph/LinearVariationGraph4.tsx
src/components/VariationGraph/PaletteVariationGraph.tsx
src/components/VariationGraph/ScalarVariationGraph.tsx
src/components/VariationGraph/SplineVariationGraph.tsx
src/components/VariationHandle.tsx
src/hooks/variationClick.ts
src/types/Block.ts
src/types/Store.ts
src/types/UIStore.ts

Now you can select multiple variations (shift click) and copy/paste them.

Variation enhancements: copy and paste

---

README.md
package.json
src/patterns/ExamplePattern.ts
src/patterns/shaders/examplePattern.frag
src/scripts/astTraversal.ts
src/scripts/generatePattern.ts

This PR adds a `yarn generatePattern <MyPatternName>` script.
It adds the appropriate pattern typescript and shader files, and it also edits the patterns.ts file to include the new pattern.

generatePattern yarn script

---

src/effects/Kaleidoscope.ts
src/effects/effects.ts
src/effects/shaders/kaleidoscope.frag
src/shaders/cartesianSpace.frag
src/shaders/conjurer_common.frag

Includes some updates to canopyToCartesianProjection() and cartesianToCanopyProjection()

Add Effect - Kaleidoscope

---

src/components/Arrangement.tsx
src/components/AudioControls.tsx
src/components/MainControls.tsx
src/components/MarkerEditorModal.tsx
src/components/Timeline.tsx
src/components/TimerControls.tsx
src/components/TimerReadout.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
src/types/AudioRegion.ts
src/types/AudioStore.ts

Use the pencil button to create markers on the timeline. Also the timeline is big now!

Improved markers

---

src/components/ParameterValue.tsx
src/components/ParameterView.tsx
src/components/Timeline.tsx
src/types/Block.ts
src/types/Layer.ts

Hopefully this fixes it - ParameterValue was updating a lot of DOM nodes every tick.

Performance issues

---

src/components/AddPatternButton.tsx
src/components/App.tsx
src/components/MainControls.tsx
src/components/PatternDrawer.tsx
src/components/PlaylistDrawer.tsx
src/components/PlaylistEditor/PlaylistEditor.tsx
src/components/PlaylistEditor/PlaylistItem.tsx
src/components/PlaylistEditor/PlaylistItemControls.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
src/data/initialPlaylist.json
src/types/AudioStore.ts
src/types/ExperienceStore.ts
src/types/PlaylistStore.ts
src/types/Store.ts
src/types/UIStore.ts

A number of things to do here still, but a hardcoded playlist works!

Partial playlist functionality

---

src/components/Menu/MenuBar.tsx
src/components/PlaylistDrawer.tsx
src/components/PlaylistEditor/AddExperienceModal.tsx
src/components/PlaylistEditor/PlaylistEditor.tsx
src/components/PlaylistEditor/PlaylistItem.tsx
src/types/PlaylistStore.ts
src/types/UIStore.ts

Most things are working now. There is only one playlist however, persisted manually in a json file. You can use the copy to clipboard button to get the json that you can then put in the `initialPlaylist.json` file. I will add persisting of the playlist later/never 👍

More playlist features

---

pages/playground.tsx
src/components/AddPatternButton.tsx
src/components/Canvas/CanopySpaceView.tsx
src/components/Canvas/DisplayCanvas.tsx
src/components/Canvas/PreviewCanvas.tsx
src/components/MainControls.tsx
src/components/PatternPlayground/DisplayModeButtons.tsx
src/components/PatternPlayground/PatternPlayground.tsx
src/components/SendDataButton.tsx
src/data/initialPlaylist.json
src/hooks/dataTransmission.ts
src/types/Store.ts

Orange button in above screenshot!

Playground send data button

---

src/components/Wavesurfer/WavesurferWaveform.tsx
src/scripts/downloadAudio.sh
src/types/AudioStore.ts
src/types/ExperienceStore.ts
src/types/PlaylistStore.ts

Really important discovery, detailed in https://github.com/SotSF/conjurer/issues/189. Hopefully less audio issues going forward! 🤞

Various, mainly audio, bug fixes

---

src/effects/ShapeMask.ts
src/effects/effects.ts
src/effects/shaders/constructMask.frag
src/effects/shaders/shapeMask.frag

Implement shape mask effect

---

src/scripts/downloadAudio.sh
src/scripts/downloadAudioExample.sh

To help with closing https://github.com/SotSF/conjurer/issues/189

Download audio scripts

---

src/components/PlayHead.tsx
src/data/initialPlaylist.json
src/scripts/downloadAudio.sh
src/types/Variations/SplineVariation.ts

And an assortment of other small updates

Spline bug

---

src/patterns/PulsePalette.ts
src/patterns/shaders/pulsePalette.frag

Even better pulse palette

---

pages/controller.tsx
src/components/PalletteEditor/PaletteEditor.tsx
src/components/PatternPlayground/DisplayModeButtons.tsx
src/components/PatternPlayground/PaletteParameterControl.tsx
src/components/PatternPlayground/PatternPlayground.tsx
src/components/PatternPlayground/ScalarParameterControl.tsx
styles/PatternPlayground.module.css

Controller mobile responsiveness

---

src/components/PatternPlayground/DisplayModeButtons.tsx
src/components/PatternPlayground/ParameterControls.tsx
src/components/PatternPlayground/PatternPlayground.tsx
src/components/PatternPlayground/ScalarParameterControl.tsx
src/components/RenderPipeline/BlockStackNode.tsx
src/components/ScalarInput.tsx
src/components/VariationControls/VariationControls.tsx
src/data/initialPlaylist.json
src/types/Block.ts
src/types/Layer.ts
src/types/PlaygroundStore.ts
src/types/Store.ts
src/types/TransferBlock.ts
src/types/UIStore.ts
src/utils/controllerWebsocket.ts

Playground periodic variations!

---

src/components/Menu/MenuBar.tsx
src/components/PatternPlayground/PatternPlayground.tsx
src/components/PatternPlayground/PresetButton.tsx
src/components/PatternPlayground/PresetsList.tsx
src/types/PlaygroundStore.ts
src/types/Preset.ts

Playground presets

---

pages/viewer.tsx
src/components/App.tsx
src/components/Arrangement.tsx
src/components/Canvas/DisplayCanvas.tsx
src/components/Display.tsx
src/components/DisplayControls.tsx
src/components/Menu/MenuBar.tsx
src/components/Timeline.tsx
src/components/ViewerPage.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
src/hooks/renderTarget.ts
src/shaders/cartesianSpace.frag
src/types/Store.ts
src/types/UIStore.ts

Viewer page

---

docs/patterns.md
docs/shaders.md
src/components/BeatGridOverlay.tsx
src/components/Canvas/CanopySpaceView.tsx
src/components/Canvas/CartesianSpaceView.tsx
src/components/Canvas/DisplayCanvas.tsx
src/components/Canvas/PreviewCanvas.tsx
src/components/PatternPlayground/DisplayModeButtons.tsx
src/components/RenderPipeline/SingleBlockRenderPipeline.tsx
src/components/SaveBeatMapModal.tsx
src/effects/shaders/chromaticAberration.frag
src/effects/shaders/cloudsMask.frag
src/patterns/BoxTime.ts
src/patterns/Opacity.ts
src/patterns/patterns.ts
src/patterns/shaders/boxTime.frag
src/patterns/shaders/logSpirals.frag
src/scripts/generatePattern.ts
src/types/Block.ts
src/types/Store.ts
src/types/UIStore.ts
yarn.lock

Miscellaneous cleanup + ray marching demo

---

src/patterns/Turbine.ts
src/patterns/patterns.ts
src/patterns/shaders/turbine.frag

Add turbine pattern

---

src/components/DisplayControls.tsx
src/components/TimelineBlockStack.tsx
src/scripts/downloadAudio.sh
src/shaders/canopy.vert
src/types/Layer.ts
src/types/Store.ts
src/types/VoiceCommandMessage.ts
src/utils/spoken.ts
src/websocket/voiceCommandHandler.ts
src/websocket/voiceCommandWebsocket.ts
src/websocket/websocketHost.ts

Basic voice command infrastructure. Shouldn't affect non voice users except for a message in the console when it fails to connect.
Also made the leds appear a bit bigger and made a segmented control for the display mode.

Voice commands

---

src/components/App.tsx
src/components/PatternDrawer.tsx
src/types/Store.ts

Lazy loading the pattern drawer is a no go

Performance improvements / bug fixes

---

next.config.js
src/components/PlaylistEditor/PlaylistEditor.tsx
src/components/TimelineBlockStack.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
src/types/AudioRegion.ts
src/types/Block.ts
src/types/Layer.ts
src/types/Store.ts
src/types/Variations/Variation.ts
src/types/VoiceCommandMessage.ts
src/utils/id.ts
src/websocket/voiceCommandHandler.ts

The console should now be significantly quieter and more useful to actually see when things go wrong.

Even more console warning suppression

---

src/components/ExperiencesTable/ExperiencesTable.tsx
src/components/PlaylistEditor/AddExperienceModal.tsx
src/components/PlaylistEditor/PlaylistEditor.tsx
src/components/PlaylistEditor/PlaylistLibrary.tsx
src/components/Timeline/TimerAndWaveform.tsx
src/components/Timeline/TimerControls.tsx
src/components/Timeline/TimerReadout.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
src/types/AudioStore.ts
src/types/PlaylistStore.ts
src/utils/array.ts

Random bug fixes for the most part. Also allows click and drag on wave surfer, Closes https://github.com/SotSF/conjurer/issues/289

Playlist page updates

---

src/components/ExperiencesTable/ExperiencesTable.tsx
src/components/LoginButton.tsx
src/components/Menu/OpenExperienceModal.tsx
src/components/PlaylistEditor/AddExperienceModal.tsx
src/components/PlaylistEditor/PlaylistEditor.tsx
src/components/PlaylistEditor/PlaylistItem.tsx
src/components/PlaylistEditor/PlaylistLibrary.tsx
src/components/PlaylistEditor/SelectablePlaylist.tsx
src/hooks/experience.ts
src/hooks/playlist.ts
src/server/routers/experienceRouter.ts
src/server/routers/playlistRouter.ts

Can now add multiple experiences to a playlist at once. Closes https://github.com/SotSF/conjurer/issues/307.

Playlist library improvements

---

package.json
src/components/BeatMapperView.tsx
src/components/Timeline/TimerAndWaveform.tsx
src/components/VariationControls/VariationControls.tsx
src/components/Wavesurfer/LazyWavesurferWaveform.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
src/components/Wavesurfer/hooks/cloneCanvas.ts
src/types/AudioStore.ts
src/types/PlaylistStore.ts
yarn.lock

Refactored Wavesurfer to use the react version. I consider it slightly better then before, but still a pretty messy part of conjurer.

Audio improvements

---

migrations/0004_recreate-experiences-table-constraints.sql
migrations/meta/0004_snapshot.json
migrations/meta/_journal.json
src/components/Menu/MenuBar.tsx

Reintroduced the uniqueness constraint that we accidentally left out after our last manual migration. Easy fix in the end cc @jeffawang 
Closes https://github.com/SotSF/conjurer/issues/326

Save new experience bug fix

---

src/components/ExperienceEditor/ExperienceEditorControls.tsx
src/components/PlaylistEditor/PlaylistItem.tsx
src/components/PlaylistEditor/PlaylistItemPlayPauseButton.tsx
src/components/Wavesurfer/WavesurferWaveform.tsx
src/types/AudioStore.ts

Just improved some subtle things about how this button works

Improve playlist item play/pause button

---

src/components/Display.tsx
src/components/DisplayControls.tsx

Full screen fix

---

src/types/PlaygroundStore.ts

Closes https://github.com/SotSF/conjurer/issues/353

Send state update when selected pattern changes

---

src/components/PatternPlayground/DisplayModeButtons.tsx
src/components/PatternPlayground/PatternPlayground.tsx
src/components/PatternPlayground/PresetButton.tsx
src/components/PatternPlayground/ScalarParameterControl.tsx
src/utils/time.ts
styles/PatternPlayground.module.css

Also restyled the page a bit to improve it's look, but there's still some quirks to work out.

Preserve preset periodic variations on save/load

---

README.md

Fixes https://github.com/SotSF/conjurer/issues/355

Update turso URL
